sudo: false # container-based infrastructure

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - apt-get update
  - apt-get upgrade cmake

before_script:
  - git clone https://github.com/daid/SeriousProton

script: cmake CMakeLists.txt -DSERIOUS_PROTON_DIR:string=../SeriousProton && make
